apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  volumes:
    - name: config
      configMap:
        name: website-index-file
        items:
          - key: index-file
            path: index.html
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
          readOnly: true

